### ISSUE TITLE
Add R linting config

### ISSUE THREAD

**Issue by ManavalanG** [uab-cgds-worthey/cgds_repo_template#12]
As R is widely used across the team, we need to add linting for R. Tasks:

1. Which linter to use?
2. What configs to use?

Reached out to the team over slack to get info.

**Comment by sdhutchins** [comment]
I'm currently using [lintr](https://lintr.r-lib.org/index.html) for the mecfs dge analysis repo.

My setup is below. I have turned off warnings as errors with the `LINTR_ERROR_ON_LINT: false` flag.

```yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: run-lintr

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}

      - name: Lint root directory
        run: lintr::lint_dir()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: false
```
